### ISSUE TITLE
example

### ISSUE THREAD

**Issue by herbi3** [LonePurpleWolf/airtouch4pyapi#11]
this isn't an issue, I didn't know how else to get in contact.

Do you have an example script available? I really just want to get the temperature from each sensor per zone

**Comment by Stephen2615** [comment]
I second that.

**Comment by jcsteh** [comment]
```
import airtouch4pyapi
airtouch = airtouch4pyapi.AirTouch("192.168.1.44") # Replace with your AirTouch IP address
await airtouch.UpdateInfo()
# Print the name and temperature of each group (AKA zone).
for group in airtouch.groups.values():
    print("{group.GroupNumber} {group.GroupName} {group.Temperature}").format(group=group))
```

The info for AC units is in airtouch.acs, while the info for groups (zones) is in airtouch.groups. You can reference these by number; e.g. `airtouch.groups[0]`, `airtouch.acs[0]`. If you want to know what attributes there are, you can try this out in an interactive Python shell:
`python -m asyncio`
Once you've run UpdateInfo, you can do something like:
`dir(airtouch.acs[0])`
to see what attributes an AC unit has.

**Comment by Stephen2615** [comment]
@jcsteh,

Thanks for providing that information. It works like a charm. Sometimes the name doesn't appear but it is no big deal.

**Comment by jcsteh** [comment]
Yeah, this is definitely occasionally unreliable. I tried fixing some bugs I spotted in the Python package, but it still wasn't entirely reliable, so I think there are likely some bugs in the AirTouch firmware as well. My suggestion for now is to call UpdateInfo, and if the info you want isn't there, retry with a small delay.

**Comment by Stephen2615** [comment]
Thanks for the work you did. It is good enough just for what I want.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by noobydp** [comment]
My airtouch unit was regularly uncontactable both in the app and with this (and similar) integrations. 

I figured out I needed to set the wifi channel and channel width to a fixed setting instead of Auto on my router. (I can't remember what channel width value worked)

After making them fixed values the airtouch has been solid and responsive 99% of the time.

**Comment by cemilbrowne** [comment]
Team, I've also added a demo.py in my latest push which might help get names etc.

**Comment by samsinnamon** [comment]
there is an example usage in 'Usage' and 'Notes' sections of the README. There is also @cemilbrowne's demo script as mentioned - if anyone wants to add to doco please feel free to PR, closing this one for now
