### ISSUE TITLE
Version mismatches

### ISSUE THREAD

**Issue by fabaff** [LonePurpleWolf/airtouch4pyapi#14]
`airtouch4pyapi` has a version mismatch in different the distribution channels:

- PyPI: 1.0.6 https://pypi.org/project/airtouch4pyapi/1.0.6/
- `main`: 1.0.4 https://github.com/LonePurpleWolf/airtouch4pyapi/blob/main/setup.py#L8

Please tag the source with 1.0.6 as mentioned in #5. Thanks

**Comment by samsinnamon** [comment]
hopefully I have understood correctly and this is now being done
