### ISSUE TITLE
Hey guys - this is a great piece of code for integrating Airtouch4 to HA. Have noticed that I need to restart HA each morning for the climate controls and sensors to update .

### ISSUE THREAD

**Issue by ddebono1984** [LonePurpleWolf/airtouch4pyapi#2]

**Comment by ddebono1984** [comment]
Not sure what's causing this, but it is almost as if the connection to Airtouch times out after a period of time (usually notice this in the morning after one of the AC systems was in the Off state

**Comment by samsinnamon** [comment]
Hi @ddebono1984, are you sure you're running on the latest version of the home assistant integration? This was widely reported a month or so ago, and since it was fixed, I haven't had anyone else report similar issues

**Comment by ddebono1984** [comment]
Thanks for the quick feedback - where would I find the latest version of the custom_component files?

**Comment by samsinnamon** [comment]
@ddebono1984 as explained in this post here https://community.home-assistant.io/t/airtouch-4-integration-aus/233295/63 if you want to run it using custom_component, people have found that if they clone/download the airtouch4-integration branch from the forked repository https://github.com/LonePurpleWolf/core/tree/airtouch4-integration, and then copy all the files in homeassistant/components/airtouch4 https://github.com/LonePurpleWolf/core/tree/airtouch4-integration/homeassistant/components/airtouch4 to their custom_components/airtouch4 folder, it works. If/when HA core accept the integration, the process will not be this complicated.
