### ISSUE TITLE
Is HomeAssistant support for the AT5 coming?

### ISSUE THREAD

**Issue by greiginsydney** [LonePurpleWolf/airtouch4pyapi#25]
Hi @samsinnamon !

We've recently had an AT5 installed here in Newcastle AU, and I'm wanting to integrate it with our Home Assistant, but that integration fails at the first hurdle:

![image](https://github.com/samsinnamon/airtouch4pyapi/assets/11004787/ee0341d7-2972-4a8a-95ce-0de72b93e07a)

Nothing appears to have been installed for me to trawl for config and log files to edit.

Am I right in guessing that it uses this underlying API, and that whilst _this_ has some AT5 support, the HA integration does not?

Are you aware of any plans to take it to that next step?

Thanks,

<br>

\- Greig.

**Comment by mrvautin** [comment]
It's been a while since I set mine up @greiginsydney but if you look at this closed issue, it might help you out: https://github.com/samsinnamon/airtouch4pyapi/issues/12

Note: My AT5 is working with HA with no issues.

**Comment by greiginsydney** [comment]
Thanks @mrvautin. That issue led me to [this goldmine of information](https://community.home-assistant.io/t/airtouch-5-integration-aus/451465/127) and ultimately to [the correct installation process](https://community.home-assistant.io/t/airtouch-5-integration-aus/451465/38?u=greiginsydney) (at least as it stands today)...

![image](https://github.com/samsinnamon/airtouch4pyapi/assets/11004787/c5b146a8-a655-4865-8474-39a52549e246)

Very exited to having made it this far! (At the next step it also correctly identified all my sensors and asked me to confirm their Area).

\- G.
