### ISSUE TITLE
Please tag releases here

### ISSUE THREAD

**Issue by onkelbeh** [LonePurpleWolf/airtouch4pyapi#5]
and, if possible, make a SDIST release on Pypi.
Thanks.

**Comment by onkelbeh** [comment]
Hope you don't mind I integrated your component also for [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository), added it with https://github.com/onkelbeh/HomeAssistantRepository/commit/e7116424fe695e68e4700075487cd0b891abc665, unfortunately I had to take it directly from the git (because you do not have releases or SDISTs, can you please confirm that EGIT_COMMIT="34783888846783c058fe79cec16feda45504f701" is correct for version 1.0.5?

**Comment by fabaff** [comment]
Would be appreciated if releases could be downloaded.
