### ISSUE TITLE
AirTouch 2 Plus integration

### ISSUE THREAD

**Issue by mcoops** [LonePurpleWolf/airtouch4pyapi#8]
Would you be open to accepting a PR to support the 2 plus or would out prefer a new library for that?

Looks like only small differences such as port, some messages and of course percentages instead of temperatures. But should be able to support that in this library. 

I think, maybe accept IP and port on init, then switch between the versions based off the port number.

**Comment by samsinnamon** [comment]
Hi @mcoops, apologies that I haven't replied to this one - if you did still want to add support for Airtouch 2 plus to this library (and then look at doing a PR for adding support for AT2+ in home assistant) definitely open to that!
